CREATE TABLE `clientes` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`CPF` VARCHAR(14) NOT NULL COLLATE 'utf8mb4_general_ci',
	`LOGRADOURO` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`BAIRRO` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CIDADE` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`UF` VARCHAR(2) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`EMAIL` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`TELEFONE` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`CELULAR` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `UID_CLIENTES_CPF` (`CPF`) USING BTREE,
	INDEX `IDX_CLIENTES_NOME` (`NOME`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;


CREATE TABLE `usuarios` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`EMAIL` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`SENHA` VARCHAR(8) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `UID_USUARIOS_EMAIL` (`EMAIL`) USING BTREE,
	INDEX `IDX_USUARIOS_NOME` (`NOME`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;