CREATE TABLE IF NOT EXISTS `clientes` (
  `ID` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `CPF` varchar(14) NOT NULL,
  `LOGRADOURO` varchar(150) NOT NULL,
  `BAIRRO` varchar(100) NOT NULL,
  `CIDADE` varchar(100) NOT NULL,
  `UF` varchar(2) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `TELEFONE` varchar(15) NOT NULL,
  `CELULAR` varchar(15) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_CLIENTES_CPF` (`CPF`),
  KEY `IDX_CLIENTES_NOME` (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;


CREATE TABLE `usuarios` (
  `ID` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SENHA` varchar(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UID_USUARIOS_EMAIL` (`EMAIL`),
  KEY `IDX_USUARIOS_NOME` (`NOME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;